site:
  theme: 'RtronTheme'
  baseUrl: 'https://rtron.io/'
  about:
    siteName: r:trån
    siteDescription: a road space model transformer for OpenDRIVE, CityGML and beyond
    social:
      other:
        - link: '/'
          label: 'Home'
          icon: 'fas fa-home'
        - link: 'https://github.com/tum-gis/rtron'
          label: 'Github'
          icon: 'fab fa-github'
        - link: 'https://www.linkedin.com/company/save-ingolstadt'
          label: 'LinkedIn'
          icon: 'fab fa-linkedin'
        - link: 'https://www.instagram.com/save.ingolstadt'
          label: 'Instagram'
          icon: 'fab fa-instagram'
        - link: '/about'
          label: 'About'
          icon: 'fas fa-info-circle'

theme:
  extraCss:
    - 'assets/css/custom.scss'
  menu:
    - type: 'submenu'
      title: 'Demos'
      itemId: 'demos'
      menu:
        - type: 'page'
          itemId: 'Model Inspection'
        - type: 'page'
          itemId: 'Model Transformations'
        - type: 'page'
          itemId: '3D City Database'
        - type: 'page'
          itemId: 'Web Map'
        - type: 'page'
          itemId: 'Desktop GIS'
        - type: 'page'
          itemId: 'Model Validation'
    - type: 'submenu'
      title: 'User Guide'
      menu:
        - type: 'wiki'
    - type: 'submenu'
      title: 'Developer Docs'
      menu:
#        - type: 'page'
#          title: "Architecture of r:trån"
#          itemId: 'Architecture of r:trån'
#        - type: 'separator'
        - type: 'sourcedocModules'
          moduleType:  'kotlindoc'
          moduleGroup: 'ui'
          node: 'packages'
        - type: 'sourcedocModules'
          moduleType:  'kotlindoc'
          moduleGroup: 'batch-processing'
          node: 'packages'
        - type: 'sourcedocModules'
          moduleType:  'kotlindoc'
          moduleGroup: 'model-processing'
          node: 'packages'
        - type: 'sourcedocModules'
          moduleType:  'kotlindoc'
          moduleGroup: 'utility'
          node: 'packages'
  metaComponents:
    - type: orchidSearch

kotlindoc:
  homePagePermalink:   'modules/:module'
  sourcePagePermalink: ':moduleType/:module/:sourceDocPath'
  modules:
    - { name: 'Documentation Module', slug: 'documentation', sourceDirs: './../../../../rtron-documentation/src/main/kotlin/', moduleGroup: 'ui' }
    - { name: 'Command-Line-Interface Module', slug: 'cli', sourceDirs: './../../../../rtron-cli/src/main/kotlin/', moduleGroup: 'ui' }
    - { name: 'Main Module', slug: 'main', sourceDirs: './../../../../rtron-main/src/main/kotlin/', moduleGroup: 'batch-processing' }
    - { name: 'Model Module', slug: 'model', sourceDirs: './../../../../rtron-model/src/main/kotlin/', moduleGroup: 'model-processing' }
    - { name: 'Reader-Writer Module', slug: 'readerwriter', sourceDirs: './../../../../rtron-readerwriter/src/main/kotlin/', moduleGroup: 'model-processing' }
    - { name: 'Transformer Module', slug: 'transformer', sourceDirs: './../../../../rtron-transformer/src/main/kotlin/', moduleGroup: 'model-processing' }
    - { name: 'Standard Module', slug: 'std', sourceDirs: './../../../../rtron-std/src/main/kotlin/', moduleGroup: 'utility' }
    - { name: 'Input-Output Module', slug: 'io', sourceDirs: './../../../../rtron-io/src/main/kotlin/', moduleGroup: 'utility' }
    - { name: 'Math Module', slug: 'math', sourceDirs: './../../../../rtron-math/src/main/kotlin/', moduleGroup: 'utility' }
