name: Build Website

on: [push, pull_request]

jobs:

  website:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run orchid build
        run: ./gradlew orchidBuild
